# Configuration principale de Symfony
framework:
    secret: '%env(APP_SECRET)%'  # Clé secrète utilisée pour le chiffrement
    #csrf_protection: true

    # La session sera démarrée UNIQUEMENT si elle est lue ou écrite.
    session: true

    #esi: true
    #fragments: true
    http_method_override: true  # Activation de la substitution de méthode HTTP

# Configuration spécifique pour les tests
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
